# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages
addons:
  apt:
    packages:
      - libgit2-dev

r_packages:
  - covr
  - lintr
after_script:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
after_success:
  - Rscript -e 'covr::codecov()'
